config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'repos/index'
  get 'greeter/hello'
  get 'greeter/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'repos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github.rb
# frozen_string_literal: true

# class representing github service
class Github
  include HTTParty
  base_uri 'https://api.github.com'
  headers  'Authorization' => 'Basic aGFtemEwODY3OkhhbXphQnJ1Y2VMZWUxOTk0',
           'User-Agent' => 'hamza0867',
           'Accept' => 'application/vnd.github.v3+json'

  def self.for(username)
    get("/users/#{username}/repos")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greeter_controller.rb
# frozen_string_literal: true

class GreeterController < ApplicationController
  def hello
    random_names = %w[James Hamza Khadija]
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end

  def goodbye; end
end

app/controllers/repos_controller.rb
# frozen_string_literal: true

class ReposController < ApplicationController
  def index
    @username = params[:username] || 'hamza0867'
    @repos = Github.for(@username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
# frozen_string_literal: true

module GreeterHelper
  def formatted_time(time)
    time.strftime('%I:%M%p')
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/greeter/goodbye.html.erb
<h1>Goodbye</h1>

app/views/greeter/hello.html.erb
<h1>Greetings <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been viewed <%= @times_displayed %> time(s) </p>
<p><%= link_to "My website", "https://hamza-benkhaldoun.odoo.com/" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repos/index.html.erb
<h1>Indexing repos of the user: <%= @username %></h1>

<% if @repos.code != 200 %>
    <p> Sorry. The user <%= @username %> doesn't exist </p>
<% else %>
    <table border="1">
        <tr> <th>name of repo</th> <th>url</th> <th>language</th> </tr>
        <% @repos.each do |repo| %>
            <tr class=<%=cycle('even', 'odd') %>>
                <td><%= repo["name"] %></td>
                <td><%= repo["url"] %></td>
                <td><%= repo["language"] %></td>
            </tr>
        <% end %>
    </table>
<%end%>